app:
    resource: "@AppBundle/Controller/"
    type:     annotation

pageNotFound:
    pattern:  /{path}
    defaults: { _controller: AppBundle:Default:pageNotFound, path: '' }
    requirements:
        path: .*
